server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 116281926130-r9qvadd7506ovr9q32lqq7r2qq27m260.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: 3a3bd55b1ab6054f3b18
            client-secret: 9c58751edfa9f9b90a757a4ec23962537b26a2d7
            scope:
              - user:email
              - user:name
              - user:location
          facebook:
            client-id: 1504689346758899
            client-secret: bbf4ca1ea0ead55c52ef25d43f618527

  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:14181/railway
    username: postgres
    password: 5A5*5C*Ed5aB5GeEB5aAdEd3d6G5geB-

  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
      cache:
        use_query_cache: false
    open-in-view: false

  application:
    name: door-hub

security:
  jwt:
    key: WC+qbHYl2B0o02421L+2UayDp2LtczY/3cSkAyErfTjmcEOXNtyjXq0un/SdY4cw

notification-service:
  eskiz:
    access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAwNTI2NzYsImlhdCI6MTcwNzQ2MDY3Niwicm9sZSI6InRlc3QiLCJzaWduIjoiZjNkMzAwYzNhZjU2M2Q3MWFlNTAyM2M5YTYxMjE1MWRiODg3ODFhOTU4MDVkNTNmYTUzZGY1ZGJlZmZhZTNhOCIsInN1YiI6IjU3NzYifQ.-Z5_qDqBldz0VWvS3CU9x-2IpqkxVpUSukILek3x660

location:
  api:
    key: AIzaSyASrs5gXw6AhjPzj_b4kmELT5NroL1Lzd4

service:
  upload:
    dir: D:\Java code\Door-Hub\src\main\resources\img